#!/bin/bash

# This script helps match Player IDs from Supabase with OneSignal subscription status
# It queries Supabase for Player IDs and checks their status in OneSignal

echo "=== OneSignal Device Subscription Checker ==="
echo ""
echo "This script helps identify which Player IDs in your database"
echo "are actually subscribed in OneSignal."
echo ""
echo "To use this:"
echo "1. Run this SQL query in Supabase to get Player IDs:"
echo ""
echo "   SELECT user_id, player_id"
echo "   FROM public.push_subscriptions"
echo "   WHERE user_id IN ("
echo "     SELECT user_id FROM public.league_members"
echo "     WHERE league_id = 'c5602a5b-4cf1-45f1-b6dc-db0670db577a'"
echo "   )"
echo "   AND is_active = true;"
echo ""
echo "2. Copy the player_id values"
echo "3. Use the diagnostic endpoint:"
echo ""
echo "   curl 'https://totl-staging.netlify.app/.netlify/functions/checkOneSignalDevices?playerIds=PLAYER_ID_1,PLAYER_ID_2,PLAYER_ID_3'"
echo ""
echo "4. Compare the results with OneSignal dashboard:"
echo "   - Look for 'subscribed: true' in the response"
echo "   - If 'subscribed: false', check OneSignal dashboard Subscription ID column"
echo "   - Verify the device shows 'Subscribed' status (green pill)"
echo ""
echo "=== Common Issues ==="
echo ""
echo "If devices show 'Never Subscribed' in OneSignal:"
echo "  - User hasn't granted push permissions"
echo "  - OneSignal SDK didn't initialize properly"
echo "  - iOS APNs delegate never fired"
echo ""
echo "Solution:"
echo "  1. Have users check iOS Settings > [Your App] > Notifications (should be ON)"
echo "  2. Delete and reinstall the app"
echo "  3. Grant push permissions when prompted"
echo "  4. Wait 10-15 seconds for OneSignal to initialize"
echo "  5. Verify device appears as 'Subscribed' in OneSignal dashboard"
echo ""

