import React from 'react'
import AsyncStorage from '@react-native-async-storage/async-storage'

// This file is generated by the Metro wrapper (`withStorybook`) and exports `view`.
// It also registers addons and story files.
import { view } from './storybook.requires'

const StorybookUIRoot = view.getStorybookUI({
  onDeviceUI: true,
  shouldPersistSelection: true,
  // Disable websocket transport to avoid simulator hangs at "Downloading 100%".
  // On-device Storybook UI works without it.
  enableWebsockets: false,
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
})

export default StorybookUIRoot

