import React from 'react'
import { Platform } from 'react-native'
import AsyncStorage from '@react-native-async-storage/async-storage'

// This file is generated by the Metro wrapper (`withStorybook`) and exports `view`.
// It also registers addons and story files.
import { view } from './storybook.requires'

const StorybookUIRoot = view.getStorybookUI({
  onDeviceUI: true,
  shouldPersistSelection: true,
  enableWebsockets: true,
  host: Platform.OS === 'android' ? '10.0.2.2' : 'localhost',
  port: 7007,
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
})

export default StorybookUIRoot

