export const TEAM_BADGES: Record<string, any> = {
  ARS: require('../../../../public/assets/badges/ARS.png'),
  AVL: require('../../../../public/assets/badges/AVL.png'),
  BHA: require('../../../../public/assets/badges/BHA.png'),
  BOU: require('../../../../public/assets/badges/BOU.png'),
  BRE: require('../../../../public/assets/badges/BRE.png'),
  BUR: require('../../../../public/assets/badges/BUR.png'),
  CHE: require('../../../../public/assets/badges/CHE.png'),
  CRY: require('../../../../public/assets/badges/CRY.png'),
  EVE: require('../../../../public/assets/badges/EVE.png'),
  FUL: require('../../../../public/assets/badges/FUL.png'),
  LEE: require('../../../../public/assets/badges/LEE.png'),
  LIV: require('../../../../public/assets/badges/LIV.png'),
  MCI: require('../../../../public/assets/badges/MCI.png'),
  MUN: require('../../../../public/assets/badges/MUN.png'),
  NEW: require('../../../../public/assets/badges/NEW.png'),
  NFO: require('../../../../public/assets/badges/NFO.png'),
  NOT: require('../../../../public/assets/badges/NOT.png'),
  TOT: require('../../../../public/assets/badges/TOT.png'),
  WHU: require('../../../../public/assets/badges/WHU.png'),
  WOL: require('../../../../public/assets/badges/WOL.png'),
  SUN: require('../../../../public/assets/badges/SUN.png'),
};

